---
# tasks file for roles/database

- name: Run database container
  docker_container:
    name: my-db
    image: gabgrge/tp-devops-database:latest
    networks:
      - name: my-network
    volumes:
      - db-volume:/var/lib/postgresql/data
    env:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: db
  vars:
    ansible_python_interpreter: /usr/bin/python3