# Use an Ubuntu base image
FROM ubuntu:latest

# Update the system and install Ansible
RUN apt-get update && apt-get install -y ansible

# Copy your Ansible playbook and roles into the Docker image
COPY ansible ansible