# Use an Ubuntu base image
FROM ubuntu:latest

# Update the system and install Ansible
RUN apt-get update && apt-get install -y ansible

# Set the working directory to /ansible
WORKDIR /ansible

# Copy your Ansible playbook and roles into the Docker image
COPY ansible/playbook.yml ansible/playbook.yml
COPY ansible/roles ansible/roles