---
# tasks file for roles/proxy

- name: Run proxy container
  docker_container:
    name: httpd
    image: gabgrge/tp-devops-httpd:latest
    networks:
      - name: my-network
    ports:
      - "80:80"
  vars:
    ansible_python_interpreter: /usr/bin/python3